// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbtewpyegsmfkaplfryr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRidGV3cHllZ3NtZmthcGxmcnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Njk5MzksImV4cCI6MjA3MzQ0NTkzOX0.F7C0_6Ov7gs6Uj3EaPLrGlH35Rd1nmQ5Aj-u6xFDGoo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});